services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duma-duma3-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - duma-duma3-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: duma-duma3-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - duma-duma3-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: duma-duma3-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: duma_duma_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - duma-duma3-network

networks:
  duma-duma3-network:
    driver: bridge

volumes:
  dbdata:
