services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duma-duma3-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - duma-duma3-network

  nginx:
    image: nginx:alpine
    container_name: duma-duma3-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - duma-duma3-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: duma-duma3-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: duma_duma_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - duma-duma3-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: duma-duma3-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - duma-duma3-network
    depends_on:
      - db

networks:
  duma-duma3-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
